docker-compose-yaml: docker-compose.yml

project: 'test'

tasks:
  post-rollout:
    - run:
        name: Install Drupal if necessary
        command: |
          if [[ ${LAGOON_GIT_SAFE_BRANCH} == "dev" ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
            drush si minimal -y --existing-config --account-name admin
          fi
        service: cli
    - run:
        name: Run Drupal deploy tasks
        command: drush -y deploy
        service: cli
    - run:
        name: Initiate Drush aliases
        command: |
          drush site:alias-convert /app/drush/sites --yes
          mv /app/drush/sites/*.yml ./drush/sites/
        service: cli

environments:
  dev:
    cronjobs:
      - name: drush cron
        schedule: '*/15 * * * *'
        command: drush cron
        service: cli
  prod:
    cronjobs:
      - name: drush cron
        schedule: '*/15 * * * *'
        command: drush cron
        service: cli
